### ISSUE TITLE
Shift Register Diagram in 2.4 doesn't match the solution

### ISSUE THREAD

**Issue by Fibonacci12358** [ucb-bar/generator-bootcamp#11]
In the solution, the output depends on io.in, but in the diagram it doesn't.

**Comment by edwardcwang** [comment]
Could you specify exactly which diagram and exactly which solution?

**Comment by Fibonacci12358** [comment]
The diagram in the shift register exercise, and the solution at the end of the exercise.

**Comment by edwardcwang** [comment]
Please be more precise (maybe include circled screenshots)

**Comment by Fibonacci12358** [comment]
![Diagram](https://i.imgur.com/2AAN8C4.png)
In the diagram, the LSB of io.out is io.in delayed by 1 clock cycle
![Solution](https://imgur.com/q0jrIiu.png)
In the solution, the LSB of io.out is io.in without any delay

**Comment by grebe** [comment]
Thanks for the good catch, @Fibonacci12358!
