### ISSUE TITLE
[request] Add an example of Chisel Printf

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/generator-bootcamp#13]
The 2.1 First Module introduces the peekPostTester. It also uses a Scala Println() to show test completion. 

It does not however show the most useful testing construct of all --- the magical Printf! 

I've gotten feedback from users who keep trying to use Println() to debug their Chisel code and became very confused.

Thanks and keep up the good work!

**Comment by grebe** [comment]
+1 on having printf somewhere. The difference between chisel `printf()` and `println()` is important to explain like other Scala vs Chisel constructs. I have a little PR, not sure if I put it in the right place.
