### ISSUE TITLE
How to deal with the issue of dead kernel?

### ISSUE THREAD

**Issue by poweihuang17** [ucb-bar/generator-bootcamp#14]
Hi, I followed the installation guide on Mac.
But I keep facing dead kernel when I opened Jupyter.
Do you know how do debug this issue?

**Comment by colinschmidt** [comment]
Can you give a more specific error message? Perhaps include whatever log prints "dead kernel"?

**Comment by poweihuang17** [comment]
@colinschmidt Thanks for your help. But I've fixed it by using this post.
https://stackoverflow.com/questions/33807635/scala-sbt-throwing-incompatibleclasschangeerror-exception

**Comment by poweihuang17** [comment]
Removing unnecessary jar file in /Library/Java/Extensions solves this.
