### ISSUE TITLE
Some typo 

### ISSUE THREAD

**Issue by poweihuang17** [ucb-bar/generator-bootcamp#18]
1. In 3.1: Taking actions based on the type of a variable when “it's” type is unknown or underspecified, for example when
(its)
2. In 3.2 Interlude:  One of the commonly used interfaces provided by Chisel is DecoupledIO, providing a ready-valid interface for transferring data. The idea is that the "sink" drives the bits signal with the data to be transferred and the valid signal when there is data to be transferred. The sink drives the ready signal when it is ready to accept data, and data is considered transferred when both ready and valid are asserted on a cycle.
(should be source)

**Comment by poweihuang17** [comment]
3. In 3.2 Interlude:The above creates a new DecoupledIO Bundle with fields

    valid: Input(Bool)
    ready: Input(Bool)
    bits: Output(UInt(8.W))
(valid should be output.)

**Comment by grebe** [comment]
Thanks for the good catches!
