### ISSUE TITLE
3.6 uses old version of getVerilog

### ISSUE THREAD

**Issue by grebe** [ucb-bar/generator-bootcamp#38]
`getVerilog` used to take `dut: () => Module` but is now `dut: Module`. 3.6 didn't get updated so it is broken.

**Comment by edwardcwang** [comment]
Other way round you mean? Other than that yes it's an oops.

```scala
def getVerilog(dut: => chisel3.core.UserModule): String = {
```

**Comment by grebe** [comment]
It used to be `dut: () => UserModule`, it is now `dut: => UserModule` (which are unfortunately different).
